# -*- coding: utf-8 -*-
"""lab 2 Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yl79X_ufQmY8puq5rPy7uoot8omK8Vv0
"""



"""**Matpotlib**

**Numpy**

**Dictionary**

**List**
"""

list = [1,2,3,4,5,6,7,8,9,10]
print (list)
total = sum(list)
print (total)
print (max(list))
print (min (list))
list.append(20)
list.remove(2)
print(list)
print(sorted(list))
print(sorted(list, reverse =True))

car = ('BMW','Mercedes','Audi')
print(car)
print(car[1])
print(car[2])
car_list = list(car_tuple)
car_list[1] = 'Toyota'
print("tuple after mods", car_list)

set1 = {1,2,3,4,5}
set2 = {5,8,3,4,5}
print ('Intersection:', set1.intersection(set2))
print ('union:', set1.union(set2))
print ('difference:', set1.difference(set2))

my_dict = {
    "name": "Afrasiab Khan",
    "age": 24,
    "city": "Abbottabad",
    "job": "Interpreter",
    "hobby": "Reading"
}
print(my_dict)

"""**tuple**

**set**

**bold text**
"""
